---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: enable ssh connections for remote management
    tags: ssh
    service:
      name: ssh
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"



- hosts: workstations
  become: true
  tasks:

    - name: install unzip
      package:
        name: unzip

    - name: install terraform
      unarchive:
        src: https://releases.hashicorp.com/terraform/1.6.2/terraform_1.6.2_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root



- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu web servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start apache2 (Ubuntu)
    tags: apache,ubuntu,apacheservice
    service:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: change timeout in apache2 config
    tags: apache2,apache,configs
    lineinfile:
      path: /etc/apache2/apache2.conf
      regexp: '^Timeout'
      line: Timeout 350
    when: ansible_distribution == "Ubuntu"
    register: apacheconfig

  - name: restart apache2
    tags: apache,configs
    service:
      name: apache2
      state: restarted
    when: apacheconfig.changed

  - name: copy default html file for site
    tags: apache,apache2,website
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644



- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package for Ubuntu DB servers
    tags: mariadb,dbserver,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"



- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest
