- name: install apache and php packages for Ubuntu web servers
  tags: apache,apache2,ubuntu
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start and enable apache
  tags: apache,ubuntu,apacheservice
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change timeout in apache2 config
  tags: apache2,apache,configs
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: '^Timeout'
    line: Timeout 340
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache


- name: copy default html file for site
  tags: apache,apache2,website
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
